polls/urls.py
from django.conf.urls.defaults import patterns, include, url
from polls.models import Poll
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('',
    (r'^(?P<poll_id>\d+)/$', 'polls.views.vote'),
    url(r'^thanks/$', direct_to_template, { 'template': 'polls/thanks.html' }, name="poll_thanks"),
)

urls.py
from django.conf.urls.defaults import *
import members

from basic.blog.feeds import BlogPostsFeed

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic.create_update import create_object
from contributors.models import LicenseAgreement

admin.autodiscover()

class FullBodyFeed(BlogPostsFeed):
    def item_description(self, item):
        return item.body

feeds = {
    'latest': FullBodyFeed,
}

from django.views.generic.simple import direct_to_template

urlpatterns = patterns('',
    #(r'^$', direct_to_template, {'template': 'index.html'}),
    url(r'^$', direct_to_template, {'template': 'new_splash.html'}, name='home'),
    url(r'^software/$', direct_to_template, {'template': 'software.html'}, name='software'),
    url(r'^install/$', direct_to_template, {'template': 'install.html'}, name='install'),

    (r'^signup_thanks', direct_to_template, {'template': 'signup_thanks.html'}),
    (r'^pilot_recommend_thanks', direct_to_template, {'template': 'pilot_recommend_thanks.html'}),
    (r'^faq', direct_to_template, {'template': 'faq.html'}),
    (r'^about', direct_to_template, {'template': 'about.html'}),
    

    (r'^signup/$', 'members.views.signup'),
    (r'^pilot_recommendation/$', 'members.views.pilot_recommendation'),
    (r'^blog/', include('basic.blog.urls')),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', 
        {'feed_dict': feeds}),
    (r'^comments/', include('django.contrib.comments.urls')),
    
    (r'^cla/$', create_object, { 'model': LicenseAgreement, 'post_save_redirect': '/cla/thanks/'}),
    (r'^cla/thanks/$', direct_to_template, { 'template': 'contributors/thanks.html'}),
    
    (r'^polls/', include('polls.urls')),   

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

contributors/models.py
from django.db import models
from django.core import validators

agree_validator = validators.RegexValidator(regex='I AGREE', message='You must type "I AGREE"')

class LicenseAgreement(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    mailing_address = models.TextField()
    country = models.CharField(max_length=255)
    telephone_number = models.CharField(max_length=255)
    fax_number = models.CharField(max_length=255, null=True, blank=True)
    corporate_contributor_information = models.TextField(null=True, blank=True)
    signature = models.CharField(max_length=255, validators=[agree_validator])
    

members/models.py
from django.db import models

class Member(models.Model):
    """
    Someone who's interested in the project.
    """
    email = models.EmailField(max_length=200)
    notes = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.email

class PilotRecommendation(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    place = models.CharField(max_length=250)
    about = models.TextField()
    photo = models.ImageField(upload_to='pilot_images')
    notes = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return (self.place + ' - ' + self.email)

polls/models.py
from django.db import models
import datetime

class Poll(models.Model):
	question = models.CharField(max_length=200)

	def __unicode__(self):
		return self.question


class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice


class Token(models.Model):
	token = models.CharField(max_length=7, unique=True)
	poll = models.ForeignKey(Poll)
	used = models.BooleanField(default=False)

	def __unicode__(self):
		return self.token


class Vote(models.Model):
	token = models.ForeignKey(Token)
	choice = models.ForeignKey(Choice)

	def __unicode__(self):
		return "Token: %s" % self.token.token

class WriteInChoice(models.Model):
	choice = models.CharField(max_length=200)
	vote = models.ForeignKey(Vote)

contributors/views.py
# Create your views here.

members/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

from models import *

class MemberForm(forms.Form):
    email = forms.EmailField() 

def signup(request):
    form = MemberForm(request.POST)
    if not form.is_valid():
        return render_to_response('new_splash.html', {'form': form })
    email = form.cleaned_data['email']
    Member(email=email).save()
    return HttpResponseRedirect('/signup_thanks')

class PilotForm(forms.ModelForm):
    class Meta:
        model = PilotRecommendation

def pilot_recommendation(request):
    if request.method == 'GET':
        form = PilotForm()
        return render_to_response('pilot_recommendation.html', {'form': form}, context_instance=RequestContext(request))
    form = PilotForm(request.POST, request.FILES)
    if not form.is_valid():
        return render_to_response('pilot_recommendation.html', {'form': form}, context_instance=RequestContext(request))
    form.save()
    return HttpResponseRedirect('/pilot_recommend_thanks')

polls/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from polls.models import Choice, Poll, Token, Vote, WriteInChoice

def display_poll(request, poll, token=None, error_message=None):
	return render_to_response('polls/form.html',
			{
			'poll': poll,
			'token': token,
			'error_message': error_message,
			}, context_instance=RequestContext(request))

def vote(request, poll_id):
	p = get_object_or_404(Poll, pk=poll_id)
	if request.method == 'GET':
		t = request.GET.get('token', None)
		return display_poll(request, poll=p, token=t)
	try:
		t = Token.objects.get(token=request.POST['token'], poll=p)
	except Token.DoesNotExist:
		return display_poll(request, poll=p, token=None,
						error_message="The poll token is invalid.")
	try:
		v = Vote.objects.get(token=t, choice__poll=p)
		return display_poll(request, poll=p, token=t,
			error_message = ("You can only vote once, and you've already voted"
							" for %s" % v.choice.choice))
	except Vote.DoesNotExist:
		pass
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return display_poll(request, poll=p, token=t,
						error_message="You didn't select a choice.")
	else:
		write_in = None
		if selected_choice.choice == 'Other':
			write_in = request.POST.get('write_in', None)
			if not write_in:
				return display_poll(request, poll=p, token=t,
					error_message="'Other' field can't be blank")

		selected_choice.votes += 1
		selected_choice.save()

		vote = Vote(token=t, choice=selected_choice)
		vote.save()
		t.used = True
		t.save()

		if write_in:
			WriteInChoice.objects.create(choice=write_in, vote=vote)
	# Always return an HttpResponseRedirect after successfully dealing
	# with POST data. This prevents data from being posted twice if a
	# user hits the Back button.
	return HttpResponseRedirect(reverse('poll_thanks'))

contributors/templates/contributors/licenseagreement_form.html
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<title>LocalWiki Contributor License Agreement</title>
	
	<style media="all"> 
    pre {
      background: #f2f2f2;
      padding: 1em;
    }
 
    body {
      max-width: 40em;
      padding: 3em;
    }
    ol {
    }
    li {
      padding: 0;
      margin: 1em;
    }
    
    #signelectronically {
      padding-top: 1em;
    }
    form div {
      width: 500px;
      padding-bottom: 1em;
    }
    form textarea {
      width: 500px;
    }
    form label {
      font-weight: bold;
      display: block;
    }
    .required-asterisk {
      color: #CC3434;
      font-size: small;
    }
    .help_text {
      display: block;
      font-size: small;
    }
    
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
      list-style-type: none;
      margin-left: 0;
      margin: 0;
      padding: 0;
      color: #CC3434;
    }
    
    #humannote {
      font-style: italic;
      color: #747474;
    }
 
  </style> 
  <style media="print"> 
    body {
      max-width: 1000em;
      padding: 1em;
    }
    pre {
      background: #fff;
      padding: 1em;
    }
    #signelectronically { display: none; }
    #humannote { display: none; }
  </style> 
	
</head>

<body {% if form.errors %}onLoad="location.href='#errors';"{% endif %}>
  
<div id="humannote">
This agreement is for your protection as well as the protection of the project; it does not change your rights to use your own contributions for any other purposes.  This agreement helps us protect the project from potentially annoying and hairy legal claims (by, say, employers).  This agreement is modeled after the <a href="http://nodejs.org/cla.html">node.js agreement</a>.
</div>

  <h1>LocalWiki</h1> 
<h2>Contributor License Agreement (&quot;Agreement&quot;)</h2> 
 
 
<p> 
Thank you for your interest in the LocalWiki open source
project being administered by Wiki Spot.  Wiki Spot is a 501(c)3 non-profit organization.
The form of license below is a document that
clarifies the terms under which You, the person listed
below, may contribute software, bug fixes, configuration
changes, documentation, or any other materials that you send
to us related to the Project (each a &quot;Contribution&quot;) to the
project.  We appreciate your participation in our project,
and your help in improving the project, so we want you to
understand what will be done with the Contributions.  This
license is for your protection as well as the protection of
Wiki Spot and its licensees; it does not change your rights to
use your own Contributions for any other purpose.  Please
complete the following information about you and the
Contributions and send us an original signed Agreement at
 
<p> 
LocalWiki <br/> 
PO Box 401044 <br/>
San Francisco, CA 94140-1044<br/> 
U.S.A.
 
<p> 
Scanned agreements may also be emailed in PDF format to
philip@localwiki.org. You should also keep a copy for your own
records.
 
<p> 
If you have questions about these terms, please contact us
at philip@localwiki.org.
 
 
<pre> 
Full name: _________________________________________________
 
Mailing Address: ___________________________________________
 
____________________________________________________________
 
Country:   _________________________________________________
 
Telephone: _________________________________________________
 
Facsimile: _________________________________________________
 
E-Mail:    _________________________________________________
</pre> 
 
 
<h3>Corporate Contributions:</h3> 
 
<p> 
If you are employed as a software engineer, or if your
employer is in the business of developing software, or
otherwise may claim rights in the Contributions, please
provide information about your employer's policy on
contributing to open source projects, including the name of
the supervisor to contact in connection with such
contributions:
 
<pre> 
 
____________________________________________________________
 
____________________________________________________________
 
____________________________________________________________
</pre> 
 
 
 
<h3>You and Wiki Spot agree:</h3> 
 
<ol> 
 
<li> 
You grant us the ability to use the Contributions in any
way.  You hereby grant to Wiki Spot, a non-exclusive,
irrevocable, worldwide, royalty-free, sublicenseable,
transferable license under all of Your relevant intellectual
property rights (including copyright, patent, and any other
rights), to use, copy, prepare derivative works of,
distribute and publicly perform and display the
Contributions on any licensing terms, including without
limitation: open source licenses like the GNU General
Public License (GPL), the GNU Lesser General Public License
(LGPL), the MIT License (MIT), the Common Public License, or the Berkeley Software
Distribution license (BSD).
Except for the licenses granted herein, You reserve all right, title, and interest in and to the Contribution.
 
<li> 
You are able to grant us these rights.  You represent
that You are legally entitled to grant the above license.
If Your employer has rights to intellectual property that
You create, You represent that You have received permission
to make the Contributions on behalf of that employer, or
that Your employer has waived such rights for the
Contributions.
 
<li> 
The Contributions are your original work.  You represent
that the Contributions are Your original works of
authorship, and to Your knowledge, no other person claims,
or has the right to claim, any right in any invention or
patent related to the Contributions.  You also represent
that You are not legally obligated, whether by entering into
an agreement or otherwise, in any way that conflicts with
the terms of this license.  For example, if you have signed
an agreement requiring you to assign the intellectual
property rights in the Contributions to an employer or
customer, that would conflict with the terms of this
license.
 
<li> 
We determine the code that is in our project.  You
understand that the decision to include the Contribution in
any project or source repository is entirely that of Wiki Spot,
and this agreement does not guarantee that the Contributions
will be included in any product.
 
<li> 
No Implied Warranties.  Wiki Spot acknowledges that, except
as explicitly described in this Agreement, the Contribution
is provided on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING, WITHOUT   LIMITATION, ANY WARRANTIES OR
CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, OR
FITNESS FOR A PARTICULAR PURPOSE.
</ol> 
 
 
<pre> 
 
 
Please sign: _______________________________________________
 
Date: ______________________________________________________
</pre> 
</div> 
 
<div id="signelectronically">
  
<a name="errors"/>
{% if form.errors %}
<ul class="errorlist">
  <li>Please correct the errors below</li>
</ul>
{% endif %}

<h2>Sign Electronically</h2> 

<form action="" method="post">
{{ form.non_field_errors }}
<div><label for="id_full_name">Full name <span class="required-asterisk">*</span></label>
  {{ form.full_name.errors }}
  {{ form.full_name }}
  </div>

<div><label for="id_email">Email <span class="required-asterisk">*</span></label>
  {{ form.email.errors }}
  {{ form.email }}
  </div>

<div><label for="id_mailing_address">Mailing address <span class="required-asterisk">*</span></label>
  {{ form.mailing_address.errors }}
  {{ form.mailing_address }}
  </div>

<div><label for="id_country">Country <span class="required-asterisk">*</span></label>
  {{ form.country.errors }}
  {{ form.country }}
  </div>

<div><label for="id_telephone_number">Telephone number <span class="required-asterisk">*</span></label>
  {{ form.telephone_number.errors }}
  {{ form.telephone_number }}
  </div>
  
<div><label for="id_fax_number">Fax number</label>
  {{ form.fax_number.errors }}
  {{ form.fax_number }}
  </div>
  
<div><label for="id_corporate_contributor_information">Corporate contributor information</label>
  <span class="help_text">
     If you are employed as a software engineer, or if your employer is in
     the business of developing software, or otherwise may claim rights in the Contributions, 
     please provide information about your employer's policy on contributing to open source 
     projects, including the name of the supervisor to contact in connection with such 
     contributions:
  </span>
  {{ form.corporate_contributor_information.errors }}
  {{ form.corporate_contributor_information }}
  </div>
  
<div><label for="id_signature">Electronic signature <span class="required-asterisk">*</span></label>
  <span class="help_text">Type "I AGREE" to accept the terms above</span>
  {{ form.signature.errors }}
  <input id="id_signature" type="text" name="signature" maxlength="255">
  </div>
<input type="submit" value="Submit">
</form>

</div>

</body>
</html>

contributors/templates/contributors/thanks.html
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<title>Thank you</title>
	
	<style media="all"> 
    pre {
      background: #f2f2f2;
      padding: 1em;
    }
 
    body {
      max-width: 40em;
      padding: 3em;
    }
    ol {
    }
    li {
      padding: 0;
      margin: 1em;
    }
  </style> 	
</head>

<body>
  
  <h1>Thank you!</h1> 
  <p>
    Your signed contributor agreement has been submitted.
  </p>

</body>
</html>

polls/templates/polls/base.html
{% extends "base.html" %}

{% block content %}
    <div class="section poll" style="min-height: 300px; padding: 2em;">
        {% block polls_content %}
        {% endblock %}
    </div>
{% endblock %}

polls/templates/polls/base_nolinks.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description"
    content="Local Wiki - Collaborative, community-owned local media" />
<link rel="image_src"
    href="http://localwiki.org/static/img/big_logo.png"/ >
<meta name="keywords"
    content="Local, Wiki, Local Wiki, Davis, Wiki, DavisWiki, Davis Wiki, Philip Neustrom, Knight Foundation, News" />

<link rel="stylesheet" type="text/css" href="/static/css/screen.css?v=5" />
<link rel="stylesheet" href="/static/css/typefaces.css" type="text/css"
    media="screen" />
<link rel="shortcut icon" href="/static/img/tinylogo_tiny2.png"
    type="image/png" />
<link rel=alternate type="application/rss+xml" href="/feeds/latest" title="LocalWiki blog RSS feed"> 
<title>LocalWiki - Collaborative,
community-owned local media</title>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25465476-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
<div id="everything">

<div id="header"><a href="/"><img
    src="/static/img/logo.png" /></a></div>

<div id="transparent"></div>

<div id="slogan">
<h1>Connecting the people, places and events that shape our
communities.</h1>
</div>

<div id="main" style="height: 300px;">


<div class="content_title"></div>

<div class="blog">
    {% block content %}{% endblock %}
</div>

</div>
</body>

</html>

polls/templates/polls/form.html
{% extends "polls/base.html" %}
{% block polls_content %}
<h3 style="text-transform: none;">{{ poll.question }}</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="/polls/{{ poll.id }}/" method="post">
{% csrf_token %}
{% if token %}
    <input type="hidden" name="token" value="{{token}}"/>
{% else %}
    <p>Your poll token from the email you received: <input type="text" name="token"/></p>
{% endif %}
<ul>
{% for choice in poll.choice_set.all %}
<li>
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    {% if choice.choice == "Other" %}
        <label for="choice{{ forloop.counter }}">{{ choice.choice }}:</label> <input type="text" name="write_in"/>
    {% else %}
        <label for="choice{{ forloop.counter }}">{{ choice.choice }}</label>
    {% endif %}
</li>
{% endfor %}
</ul>
<input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/thanks.html
{% extends "polls/base.html" %}
{% block polls_content %}
<h1>Thank you for voting!</h1>
<p>Your vote has been recorded.  Stay tuned for more updates very soon!</p>
{% endblock %}

templates/base_old.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description"
	content="Local Wiki - Collaborative, community-owned local media" />
<link rel="image_src"
	href="http://localwiki.org/static/img/big_logo.png"/ >
<meta name="keywords"
	content="Local, Wiki, Local Wiki, Davis, Wiki, DavisWiki, Davis Wiki, Philip Neustrom, Knight Foundation, News" />

<link rel="stylesheet" type="text/css" href="/static/css/screen.css?v=5" />
<link rel="stylesheet" href="/static/css/typefaces.css" type="text/css"
	media="screen" />
<link rel="shortcut icon" href="/static/img/tinylogo_tiny2.png"
	type="image/png" />
<link rel=alternate type="application/rss+xml" href="/feeds/latest" title="LocalWiki blog RSS feed"> 
<title>{% block title %}LocalWiki - Collaborative,
community-owned local media{% endblock %}</title>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25465476-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
<div id="everything">

<div id="header"><a href="/"><img
	src="/static/img/logo.png" /></a></div>

<div id="transparent"></div>

<div id="slogan">
<h1>Connecting the people, places and events that shape our
communities.</h1>
</div>

<div id="main">
<div class="actionArea" style="padding-top: 30px; margin-left: 40px; margin-bottom: 20px; width: 350px">
  <h4><a href="/pilot_recommendation">Recommend a community</a></h4>
  <div class="pilot" style="text-align: center; margin-top: 5px;">
    <p>We need your help finding great pilot communities for the
    project! Have an idea? Please <strong><a
      href="/pilot_recommendation">let us know!</a></strong></p>
  </div>

  <div class="signup">
    <h4>Help out & get more info!</h4>
    <div style="text-align: center; margin-top: 2px;">
      <p>Help out and get more information as we get started. This is an
      entirely open source effort, from the start!</p>
      {{ form.email.errors }}
      <form method="POST" action="/signup/">Email: <input id="id_email"
        name="email" maxlength="200" type="text" /> <input type="image"
        id="signup_submit" src="/static/img/signup.png" value="Submit"
        alt="Submit"></form>
    </div>
  </div>
</div>

<div class="content_title">{% block content_title %}{% endblock %}</div>

<div class="blog">{% block content %}{% endblock %}</div>

<div id="footer">
{% include "nav.html" %}
<div class="note">
<p>For questions, media inquiries or, well, just about anything,
email <a href="mailto:contact@localwiki.org">contact@localwiki.org</a>.</p>
<p>{#Supported by a Knight News Challenge grant from the <a href="http://knightfoundation.org">John S. and James L. Knight Foundation</a>.#} We are a 501(c)3 non-profit organization. Content on this site is licensed under a <a href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share Alike 3.0 Unported License</a>.</p>
</div>
</div>
</div>
</div>

</body>

</html>

templates/blog/base_blog.html
{% extends "base.html" %}


{% block body_class %}blog{% endblock %}

{% block content %}
<div class="section blog">{% block blog_content %}{% endblock %}</div>
{% endblock %}

templates/blog/category_detail.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Posts for" %} {{ category.title }}{% endblock %}
{% block body_class %}{{ block.super }} category_detail{% endblock %}
{% block body_id %}category_{{ category.id }}{% endblock %}


{% block content_title %}
  <h2>{% trans "Posts for" %} {{ category.title }}</h2>
{% endblock %}


{% block blog_content %}
  <div class="post_list">
    {% for post in object_list %}
    <div>
      <h3 class="title"><a href="{{ post.get_absolute_url }}" title="{% trans "View this post" %}">{{ post.title }}</a></h3>
      <p class="date">{{ post.publish|date:"Y F d" }}</p>
      <p class="tease">{{ post.tease|safe }}</p>
    </div>
    {% endfor %}
  </div>
{% endblock %}

templates/blog/category_list.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post categories" %}{% endblock %}
{% block body_class %}{{ block.super }} category_list{% endblock %}


{% block content_title %}
  <h2>{% trans "Post categories" %}</h2>
{% endblock %}


{% block blog_content %}
  <ul class="link_list">
    {% for category in object_list %}
    <li><a href="{{ category.get_absolute_url }}" title="{% trans "View posts in this category" %}">{{ category }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/blog/post_archive_day.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post archive for" %} {{ day|date:"d F Y" }}{% endblock %}
{% block body_class %}{{ block.super }} post_archive_day{% endblock %}


{% block content_title %}
  <h2>{% trans "Post archive for" %} {{ day|date:"d F Y" }}</h2>
{% endblock %}


{% block blog_content %}
  <div class="post_list">
    {% for post in object_list %}
    <div>
      <h3 class="title"><a href="{{ post.get_absolute_url }}" title="{% trans "View this post" %}">{{ post.title }}</a></h3>
      <p class="date">{{ post.publish|date:"Y F d" }}</p>
      <p class="tease">{{ post.tease|safe }}</p>
    </div>
    {% endfor %}
  </div>
{% endblock %}

templates/blog/post_archive_year.html
{% extends "blog/base_blog.html" %}

{% load i18n %}

{% block title %}{% trans "Post archive for" %} {{ year }}{% endblock %}
{% block body_class %}{{ block.super }} post_archive_year{% endblock %}


{% block content_title %}
  <h2>{% trans "Post archive for" %} {{ year }}</h2>
{% endblock %}


{% block block_content %}  
  <ul class="link_list">
    {% for month in date_list %}
    <li><a href="{% url blog_index %}{{ year }}/{{ month|date:"b" }}/" title="{% trans "View items posted this month" %}">{{ month|date:"F" }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/pilot_recommendation.html
{% extends "base.html" %}

{% block content %}
<div class="page">

<div class="section overview">
    <h2 id="title">Recommend a focus community</h2> 
                <form enctype="multipart/form-data" method="POST" action="/pilot_recommendation/" id="pilot_recommendation">
{{ form.name.errors }}
                <p><label for="id_name">Your name:</label></p><p><input id="id_name" type="text" name="name" maxlength="200" {% if form.name.data %}value="{{form.name.data}}"{% endif%} /></p>
{{ form.email.errors }}
<p><label for="id_email">Your email:</label></p><p><input id="id_email_pilot" type="text" name="email" maxlength="200" {% if form.email.data %}value="{{form.email.data}}"{% endif %}/></p>
{{ form.place.errors }}
<p><label for="id_place">Town / City (please include state or country):</label></p><p><input id="id_place" type="text" name="place" maxlength="250" {% if form.place.data %}value="{{form.place.data}}"{% endif %}/></p>
{{ form.about.errors }}
<p><label for="id_about">Tell us about yourself and this community!  For example, who might work with you on this project?:</label></p><p><textarea id="id_about" rows="10" cols="40" name="about">{% if form.about.data %}{{form.about.data}}{% endif %}</textarea></p>
{{ form.photo.errors }}
<p><label for="id_photo">Attach a photo of something unique and interesting in your community!:</label></p><p><input type="file" name="photo" id="id_photo" /></p>
                <input type="submit" value="Submit!" id="pilot_submit"/> </form>
                </form>
                <br/>
   </div>
</div>
{% endblock %}